#!/usr/bin/env python3
"""Assemble the complete GitHub Pages site with fresh main-branch API docs."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKER = ".roc-ansi-www-preview"
VERSION_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
VERSIONS_PLACEHOLDER = "<!--VERSIONS-->"


def prepare_output(output: Path) -> None:
    if output.exists():
        if not (output / MARKER).is_file():
            raise SystemExit(f"Refusing to replace {output}: it was not created by this script")
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / MARKER).write_text("generated by scripts/assemble_www.py\n", encoding="utf-8")


def write_version_list(output: Path) -> None:
    """Link every archived release's documentation from the landing page."""
    index = output / "index.html"
    document = index.read_text(encoding="utf-8")
    if VERSIONS_PLACEHOLDER not in document:
        raise SystemExit(f"{index} is missing {VERSIONS_PLACEHOLDER}")
    versions = sorted(
        (path.name for path in output.iterdir() if path.is_dir() and VERSION_RE.fullmatch(path.name)),
        key=lambda name: tuple(int(part) for part in name.split(".")),
        reverse=True,
    )
    items = "".join(f'<li><a href="./{version}/">{version}</a></li>' for version in versions)
    markup = f'<ul class="version-list">{items}</ul>' if versions else "<p>No archived releases yet.</p>"
    index.write_text(document.replace(VERSIONS_PLACEHOLDER, markup, 1), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--roc", default=os.environ.get("ROC", "roc"))
    parser.add_argument("--output", type=Path, default=ROOT / ".roc-ansi-tmp" / "www-preview")
    parser.add_argument("--url-root", default="/roc-ansi/main")
    args = parser.parse_args()

    output = args.output.resolve()
    prepare_output(output)
    shutil.copytree(ROOT / "www", output, dirs_exist_ok=True)
    main_docs = output / "main"
    if main_docs.exists():
        shutil.rmtree(main_docs)

    env = os.environ.copy()
    env["ROC_DOCS_URL_ROOT"] = args.url_root
    subprocess.run(
        [args.roc, "docs", "package/main.roc", f"--output={main_docs}"],
        cwd=ROOT,
        env=env,
        check=True,
    )
    shutil.copy2(main_docs / "favicon.svg", output / "favicon.svg")
    subprocess.run([sys.executable, "scripts/generate_example_pages.py", str(output)], cwd=ROOT, check=True)
    subprocess.run([sys.executable, "scripts/enhance_docs_site.py", str(output)], cwd=ROOT, check=True)
    write_version_list(output)
    print(f"Assembled Pages site in {output}")


if __name__ == "__main__":
    main()
